import type { AppProps } from 'next/app';
import Head from 'next/head';
import Image from 'next/image';
import '../styles/globals.css';
import logo from '../public/brain.png';

export default function App ({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Imaginando</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/brainstorming.ico' />
      </Head>
      <header className='flex h-16 items-center bg-slate-800'>
        <Image src={logo} alt='Imaginando' width={100} />
        <p className='text-xl text-gray-200'>Imaginando</p>
      </header>
      <main className='h-screen bg-slate-900'>
        <Component {...pageProps} />
      </main>
    </>
  );
}
